routes/admin.php
<?php

Route::redirect('admin', 'admin/postcards');

Route::get('admin/postcards', 'PostcardController@index');
Route::post('admin/postcards', 'PostcardController@store');
Route::delete('admin/postcards/{postcard}', 'PostcardController@delete');

routes/web.php
<?php

Route::view('/', 'pages/home/index')->name('home');

Route::view('laravel', 'pages/laravel/index')->name('laravel');

Route::view('web-development', 'pages/web-development/index')->name('web-development');

Route::prefix('about-us')->group(function () {
    Route::view('/', 'pages/about/index')->name('about');

    collect(config('team.members'))->each(function (string $personName) {
        Route::redirect($personName, "/about-us/#{$personName}");
    });
});

Route::prefix('open-source')->group(function () {
    Route::get('/', 'OpenSourceController@index')->name('open-source.index');
    Route::get('postcards', 'PostcardController@index')->name('open-source.postcards');
    Route::get('packages', 'OpenSourceController@packages')->name('open-source.packages');
    Route::get('projects', 'OpenSourceController@projects')->name('open-source.projects');
});

Route::prefix('vacancies')->group(function () {
    Route::redirect('free-application', '/vacancies/spontaneous-application');

    Route::view('/', 'pages.vacancies.index')->name('vacancies.index');
    Route::view('internships', 'pages.vacancies.internship')->name('vacancies.internship');

    Route::get('{slug}', function ($slug) {
        return view("pages.vacancies.{$slug}");
    })->name('vacancies.show');
});

Route::view('legal', 'pages.legal.index')->name('legal.index');
Route::view('privacy', 'pages.legal.privacy')->name('legal.privacy');
Route::view('disclaimer', 'pages.legal.disclaimer')->name('legal.disclaimer');
Route::view('general-conditions', 'pages.legal.generalConditions')->name('legal.conditions');
Route::view('gdpr', 'pages.legal.gdpr')->name('legal.gdpr');

Route::view('offline', 'errors.offline')->name('offline');

app/Models/Contributor.php
<?php

namespace App\Models;

class Contributor extends Model
{
    public function getStyledUsernameAttribute(): string
    {
        return '@' . $this->username;
    }
}

app/Http/Controllers/OpenSourceController.php
<?php

namespace App\Http\Controllers;

use App\Http\Resources\RepositoryResource;
use App\Models\Contributor;
use App\Models\Issue;
use App\Models\Repository;

class OpenSourceController extends Controller
{
    public function index()
    {
        $repositories = RepositoryResource::collection(
            Repository::getHighlightedPackages()
        )->resolve();

        $issues = Issue::latest()->take(2)->get();

        $contributor = Contributor::first();

        return view('pages.open-source.index', compact('repositories', 'issues', 'contributor'));
    }

    public function packages()
    {
        $repositories = RepositoryResource::collection(
            Repository::getAllPackages()
        )->resolve();

        return view('pages.open-source.packages', compact('repositories'));
    }

    public function projects()
    {
        $repositories = RepositoryResource::collection(
            Repository::getAllProjects()
        )->resolve();

        return view('pages.open-source.projects', compact('repositories'));
    }
}

resources/views/pages/open-source/partials/banner-packages.blade.php
<section id="banner" class="banner" role="banner">
    <div class="wrap-8">
        @include('pages.open-source.partials.menu')

        <div class="self-start sm:spanx-3 mt-8 | sm:grid-text-right sm:mt-0 | md:spanx-4 | print:spanx-7">
            <h1 class="banner-slogan">
            Open source packages
            </h1>
            <p class="banner-intro">
            {{ ucfirst(App\Models\Repository::humanReadableDownloadCount()) }} downloads and <span class="icon">{{ svg('icons/far-chart-line') }}</span>
            </p>
        </div>
    </div>
</section>

resources/views/pages/open-source/partials/banner-postcards.blade.php
<section id="banner" class="banner" role="banner">
    <div class="wrap-8">
        @include('pages.open-source.partials.menu')

        <div class="self-start sm:spanx-3 mt-8 | sm:grid-text-right sm:mt-0 | md:spanx-4 | print:spanx-7">
            <h1 class="banner-slogan">
            Greetings <br>to Antwerp
            </h1>
            <p class="banner-intro">
            Postcardware in action
            </p>
        </div>
    </div>
</section>

resources/views/pages/open-source/partials/banner-projects.blade.php
<section id="banner" class="banner" role="banner">
    <div class="wrap-8">
        @include('pages.open-source.partials.menu')

        <div class="self-start sm:spanx-3 mt-8 | sm:grid-text-right sm:mt-0 | md:spanx-4 | print:spanx-7">
            <h1 class="banner-slogan">
            Open source projects
            </h1>
            <p class="banner-intro">
            Boiling stuff from the lab
            </p>
        </div>
    </div>
</section>

resources/views/pages/open-source/partials/banner.blade.php
<section id="banner" class="banner" role="banner">
    <div class="wrap-8">
        @include('pages.open-source.partials.menu')

        <div class="self-start sm:spanx-3 mt-8 | sm:grid-text-right sm:mt-0 | md:spanx-4 | print:spanx-7">
            <h1 class="banner-slogan">
                From the<br>
                (open) source
            </h1>
            <p class="banner-intro">
                Packages and side projects <br>for Laravel &amp; JavaScript
            </p>
        </div>
    </div>
</section>

resources/views/pages/open-source/partials/contributor.blade.php
<div class="flex items-center mt-8 my-6">
    <div class="avatar">
        <img src="{{ $contributor->avatar_url }}">
    </div>
    <div class="ml-4">
        <h3 class="title-sm">
            {{ $contributor->name }} <span class="icon fill-pink">{{ svg('icons/far-award') }}</span>
        </h3>
        <p class="text-xs text-grey mt-2 links-underline links-grey">
            Thank you <a class="" href="https://github.com/{{ $contributor->username }}">{{ $contributor->styled_username }}</a> <br>for your help on <a class="" href="{{ $contributor->repository_url }}">spatie/{{ $contributor->repository_name }}</a>
        </p>
    </div>
</div>

resources/views/pages/open-source/partials/insights.blade.php
<h2 class="title-sm">
    Latest insights
    <div class="title-subtext text-pink-dark">
        From the team
    </div>
</h2>
@foreach ($insights as $insight)
     <p class="mt-4">
        <a class="link link-black" href="{{ $insight->url }}" target="_blank" rel="noreferrer noopener">{{ $insight->title }}</a>
        <br>
        <span class="text-xs text-grey">
            {{ $insight->created_at->format('M jS Y') }}
            <span class="char-separator" >•</span>
            <a class="link-underline link-blue" href="{{ $insight->url }}" target="_blank" rel="noreferrer noopener">{{ $insight->website }}</a>
        </span>
    </p>
@endforeach

resources/views/pages/open-source/partials/menu.blade.php
<div class="banner-menu | print:hidden">
  {{ Menu::opensource() }}
</div>

resources/views/pages/open-source/partials/news.blade.php
<section id=news class="section">
    <div class="wrap-6">
        <div class="sm:spanx-3">
            <div class="line-l">
                <h2 class="title-sm">
                    <a href='https://github.com/issues?q=is%3Aopen+is%3Aissue+user%3Aspatie+is%3Apublic+label%3A%22good+first+issue%22'
                       class="link-black">Help us out</a>
                    <div class="title-subtext text-pink-dark">
                        Easy issues to solve
                    </div>
                </h2>
                @foreach($issues as $issue)
                    <p class="mt-4">
                        <a href="{{ $issue->url }}" target="_blank" rel="nofollow noreferrer noopener" class="link link-black">
                            {{ $issue->title }}
                        </a>
                        <br>
                        <span class="text-xs text-grey">
                            <a href="{{ $issue->repository->url }}" target="_blank" rel="nofollow noreferrer noopener">
                                {{ $issue->repository->name }}
                            </a>
                            <span class="char-separator" >•</span>
                            <a href="{{ $issue->url }}" target="_blank" rel="nofollow noreferrer noopener" class="link-underline link-blue">
                                #{{ $issue->number }}
                            </a>
                        </span>
                    </p>
                @endforeach
                <p class="mt-4">
                    <a class="link-underline link-blue"
                       href='https://github.com/issues?q=is%3Aopen+is%3Aissue+user%3Aspatie+is%3Apublic+label%3A%22good+first+issue%22'>
                        All easy issues on GitHub…
                    </a>
                </p>
            </div>
            @if($contributor)
                <div class="mt-12 pl-4">
                    <p>
                        We would be nowhere without the help of the great community.
                        Just look at this wonderful human being!
                    </p>
                    <div class="mt-4">
                        @include('pages.open-source.partials.contributor')
                    </div>
                </div>
            @endif
        </div>
        <div class="sm:spanx-3">
            <div class="line-l pt-8 | sm:pt-0">
                @include('pages.open-source.partials.insights')
            </div>
        </div>
    </div>
</section>

resources/views/pages/open-source/partials/postcard-countries.blade.php
<div class="wrap mt-16">
    <div class="inset-blue pb-16">
        <div class="wrap-inset md:items-center" style="--cols: 1fr 1fr">
            <h2 class="title-xl">
                Most active <br>countries
            </h2>
            <ul class="text-2xl leading-tight">
                @foreach($countries as $country)
                    <li class="flex items-center my-4">
                        <span class="inline-flex flex-none mr-4 rounded-full w-8 h-8 text-xs bg-blue font-sans-bold text-white items-center justify-center shadow">{{ $country['postcard_count'] }}</span>
                        {{ $country['name'] }}
                    </li>
                @endforeach
            </ul>
        </div>
    </div>
</div>

resources/views/pages/open-source/partials/postcard-intro.blade.php
<section id="postcards" class="section">
    <div class="wrap-6">
        <div class="sm:spanx-6">
            <div class="markup links-underline links-blue">
                <p class="text-lg">
                    All of our packages are postcardware: free to use if you send us a postcard.
                    <br>
                   So cool to get snail mail from all over the world!
                </p>
            </div>
        </div>
    </div>
</section>

resources/views/pages/open-source/partials/postcard.blade.php
<div class="illustration is-postcard" style="left: {{ rand(-20, +20) }}px; top: {{ rand(-20, +10) }}px">
    {{ $postcard->getFirstMedia() }}

    <div class="mt-4 text-xs links-underline links-black leading-tight">
        @if($postcard->sender)
            {!! $postcard->sender !!}
        @endif

        @if ($postcard->location)
            <div class="flex items-baseline text-grey my-2">
                <span>{{ $postcard->location }}</span>
                <span class="icon ml-1 flex-none fill-grey-lighter">{{ svg('icons/fas-map-marker-alt') }}</span>
            </div>
        @endif
    </div>
</div>

resources/views/pages/open-source/partials/postcards.blade.php
<section id="postcards" class="section pt-0 -mt-8 overflow-visible">
    <div class="wrap-gallery items-start">
        @foreach($postcards as $postcard)
                @include('pages.open-source.partials.postcard')
        @endforeach
    </div>
</section>

resources/views/pages/open-source/partials/resources.blade.php
<section id="resources" class="section">
    <div class="wrap">
        <div class="inset-blue">
            <div class="wrap-inset md:items-center" style="--cols: 1fr 1fr">
                <h2 class="title-xl">
                    Popular <br>Resources
                </h2>
                <ul class="text-2xl links-black links-underline bullets bullets-blue">
                        <li><span class="icon">{{ svg('icons/far-angle-right') }}</span> <a href="{{ route('open-source.packages') }}">Search all packages</a></li>
                        <li><span class="icon">{{ svg('icons/far-angle-right') }}</span> <a href="https://docs.spatie.be">All documentation</a></li>
                        <li><span class="icon">{{ svg('icons/far-angle-right') }}</span> <a href="https://github.com/spatie">GitHub</a></li>
                    </ul>
            </div>
        </div>
    </div>
</section>

resources/views/pages/open-source/partials/support.blade.php
<section id="support" class="section">
    <div class="wrap-8">
        <div class="sm:spanx-3 sm:startx-2">
            <div class="markup links-underline links-blue">
               <h2 class="title-2xl">Support us
                </h2>
                <p class="text-lg">
                    A lot of our packages are postcardware: free to use if you send us a postcard. All cards will be published on <a href="{{ route('open-source.postcards') }}">our wall</a>.
                </p>
                <p class="text-lg">
                    With a growing portfolio of {{ App\Models\Repository::count() }} packages, maintaining and supporting all issues and updates has become a substantial portion of our workload.<br>
                    Reach out and <a href="https://patreon.com/spatie" target="_blank" rel="noreferrer noopener">support us</a> on Patreon.
                    <a href="https://patreon.com/spatie" target="_blank" rel="noreferrer noopener"><img class="mt-8 h-10" src="/images/patreon.png"></a>
                </p>
            </div>
        </div>
        <div class="sm:spanx-3 sm:startx-6">
            <a class="illustration is-right is-rotated is-postcard-without-caption h-full" href="https://patreon.com/spatie" >
                {{ image('support.jpg') }}
            </a>
        </div>
    </div>
</section>