routes/admin.php
<?php

Route::redirect('admin', 'admin/postcards');

Route::get('admin/postcards', 'PostcardController@index');
Route::post('admin/postcards', 'PostcardController@store');
Route::delete('admin/postcards/{postcard}', 'PostcardController@delete');

routes/web.php
<?php

Route::view('/', 'pages/home/index')->name('home');

Route::view('laravel', 'pages/laravel/index')->name('laravel');

Route::view('web-development', 'pages/web-development/index')->name('web-development');

Route::prefix('about-us')->group(function () {
    Route::view('/', 'pages/about/index')->name('about');

    collect(config('team.members'))->each(function (string $personName) {
        Route::redirect($personName, "/about-us/#{$personName}");
    });
});

Route::prefix('open-source')->group(function () {
    Route::get('/', 'OpenSourceController@index')->name('open-source.index');
    Route::get('postcards', 'PostcardController@index')->name('open-source.postcards');
    Route::get('packages', 'OpenSourceController@packages')->name('open-source.packages');
    Route::get('projects', 'OpenSourceController@projects')->name('open-source.projects');
});

Route::prefix('vacancies')->group(function () {
    Route::redirect('free-application', '/vacancies/spontaneous-application');

    Route::view('/', 'pages.vacancies.index')->name('vacancies.index');
    Route::view('internships', 'pages.vacancies.internship')->name('vacancies.internship');

    Route::get('{slug}', function ($slug) {
        return view("pages.vacancies.{$slug}");
    })->name('vacancies.show');
});

Route::view('legal', 'pages.legal.index')->name('legal.index');
Route::view('privacy', 'pages.legal.privacy')->name('legal.privacy');
Route::view('disclaimer', 'pages.legal.disclaimer')->name('legal.disclaimer');
Route::view('general-conditions', 'pages.legal.generalConditions')->name('legal.conditions');
Route::view('gdpr', 'pages.legal.gdpr')->name('legal.gdpr');

Route::view('offline', 'errors.offline')->name('offline');

app/Models/Member.php
<?php

namespace App\Models;

use Spatie\SchemaOrg\Person;
use Spatie\SchemaOrg\Schema;

class Member extends Model
{
    public function scopeFounder($query)
    {
        return $query->where('founder', true);
    }

    public function scopeEmployee($query)
    {
        return $query->where('founder', false);
    }

    public function getSlugAttribute(): string
    {
        return strtolower($this->first_name);
    }

    public function getWebsiteDomainAttribute(): string
    {
        return parse_url($this->website)['host'] ?? '';
    }

    public function schema(): Person
    {
        return Schema::person()
            ->name("{$this->first_name} {$this->last_name}")
            ->jobTitle($this->role)
            ->url(array_values(array_filter([
                $this->website,
                $this->twitter ? "https://twitter.com/{$this->twitter}" : null,
            ])))
            ->if($this->public_email, function ($person) {
                $person->email($this->email);
            });
    }
}

resources/views/pages/about/partials/banner-contact.blade.php
<p class="text-2xl mt-12 grid-rows gapx-16 gapy-4 | md:mt-16 md:grid-cols justify-start items-start" style="--cols: auto auto auto">
    <span>
        <a class="link link-black" href="mailto:info@spatie.be">info@spatie.be</a>
        <br>
        <a class="link link-black" href="https://twitter.com/intent/tweet?text=Dear+@spatie_be+…" target="_blank" rel="noreferrer noopener">@spatie_be</a>
        <br>
        <a class="link link-black" href="#tel">+32 3 292 56 79</a>
    </span>
    <a class="group block link link-black" href="https://goo.gl/maps/Qe39fmR5RTC2" target="_blank" rel="noreferrer noopener">
            Samberstraat 69D
            <br>
            2060 Antwerp <br>Belgium
            <span class="icon px-2 fill-pink group-hover:opacity-75 transition-fill transition-fast">
                {{ svg('icons/fas-map-marker-alt') }}
            </span>
        </span>
    </a>
    @isset($financialContacts)
        <span class="text-xs mt-2 leading-loose">
            <span class="w-8 inline-block text-grey">VAT</span> BE0809.387.596
            <br>
            {{-- IBAN nr spaced out for readability but selectable with double click. --}}
            <span class="w-8 inline-block text-grey">IBAN</span> BE66<span class=ml-1>3</span>631<span class=ml-1>2</span>787<span class=ml-1>5</span>443
            <br>
            <span class="w-8 inline-block text-grey">BIC</span> BBRUBEBB
        </span>
    @endisset
</p>

resources/views/pages/about/partials/banner.blade.php
<section id="banner" class="banner" role="banner">
    <div class="wrap">
        <h2 class="banner-slogan">
            Glad you found us
        </h2>
        @include('pages.about.partials.banner-contact',['financialContacts' => true])
    </div>
</section>

resources/views/pages/about/partials/cta.blade.php
<section id="cta" class="section">
    <div class="wrap">
        <div class="inset-green">
            <div class="wrap-inset md:items-end" style="--cols: 1fr 2fr">
                <div class="links-underline links-white">
                    <p class="text-2xl">
                        Enough about us.
                    </p>
                </div>
                <h2 class="title-xl | grid-text-right">
                    <a class="link-white link-underline" href="{{ mailto(
'Why I\'m considering Spatie',
'Tell us as much as you can about
- your online project
- your planning
- your budget
- …

Anything that helps us to start straightforward!'
) }}">What brought <br>you here</a>?
                </h2>
            </div>
        </div>
    </div>
</section>

resources/views/pages/about/partials/member.blade.php
<div id="{{ $member->slug }}" class="wrap-6 items-start section">
    <div class="sm:spanx-2">
        <h3 class="title-sm">
            {{ $member->first_name }} {{ $member->last_name }}
            <div class="title-subtext text-grey-light">{{ $member->role }}</div>
        </h3>
        <div class="avatar mt-4">
            {{ gravatar_img($member->email) }}
        </div>
    </div>
    <div class="line-l markup links-underline links-blue | sm:spanx-4 text-sm">
        <p>{{ $member->description }}</p>
        <ul class="text-xs">
            @if($member->public_email)
                <li><a href="mailto:{{ $member->email }}">{{ $member->email }}</a></li>
            @endif
            @if($member->twitter)
                <li><a href="https://twitter.com/{{ $member->twitter }}">{{ '@'.$member->twitter }}</a></li>
            @endif
            @if($member->website)
                <li><a href="{{ $member->website }}">{{ $member->website_domain }}</a></li>
            @endif
        </ul>
    </div>
</div>

resources/views/pages/about/partials/outro.blade.php
<section id="company" class="section">
    <div class="wrap">
       <h2 class="title-2xl">
            About <br>Spatie
        </h2>
    </div>
    <div class="wrap-6 | items-start">
        <div class="sm:spanx-4">
            <div class="markup links-underline links-blue">
                <p class="text-lg">
                    We design, build and support websites, webshops and applications —since 2004.
                </p>
                <p class="text-lg">
                    We prefer analysis, clear-cut advice and solid technology over momentary fads. Our sites are built with modern standards, and optimized for performance on all types of devices.
                </p>
                <p class="text-lg">
                    Almost every aspect of our job builds upon the work of others.
                    We greatly value open source and try to give back to the community whenever possible.
                </p>
                <p class="text-lg">
                    There is a strong mentality to stay on top of things: through Slack, in-house presentations or conferences.
                    A part of our workload is dedicated to open source and side projects.
                    You can spot team members in user groups or as conference speakers as well.
                </p>
            </div>
        </div>
        <div class="line-l | sm:spanx-2 sm:startx-5">
            <p class="markup text-grey text-xs">
                ‘Spatie’ is Dutch for ‘space’, the character between 2 words.
                <br>You pronounce it /'spɑːsiː/.
            </p>
        </div>
    </div>
</section>

resources/views/pages/about/partials/team.blade.php
<section id="team">
    <div class="wrap">
        <h2 class="title line-after mb-16">Meet the team</h2>
    </div>
    @foreach($members as $member)
        @include('pages.about.partials.member')
    @endforeach
</section>